//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "edit_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub submission_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub event_type: String,
    pub position: i32,
    pub char_count: i32,
    pub occurred_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "submission_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub submissions: HasOne<super::submissions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
