//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "exercise_assignments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub exercise_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: Uuid,
    #[sea_orm(column_type = "Text", nullable)]
    pub non_participation_reason: Option<String>,
    pub reason_set_by: Option<Uuid>,
    pub reason_set_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "exercise_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub exercises: HasOne<super::exercises::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "reason_set_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users_2: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users_1: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
