//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "exercises")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    pub enabled: bool,
    pub question_count: i32,
    pub start_time: Option<DateTimeWithTimeZone>,
    pub end_time: Option<DateTimeWithTimeZone>,
    pub duration_limit: Option<String>,
    pub min_questions_required: Option<i32>,
    pub flag_fails: bool,
    pub max_paste_chars: Option<i32>,
    pub max_focus_loss: Option<i32>,
    pub min_edit_events: Option<i32>,
    pub min_response_length: Option<i32>,
    pub pass_mark: Option<Decimal>,
    #[sea_orm(column_type = "Text")]
    pub exercise_type: String,
    #[sea_orm(has_many)]
    pub exercise_assignments: HasMany<super::exercise_assignments::Entity>,
    #[sea_orm(has_many)]
    pub questions: HasMany<super::questions::Entity>,
    #[sea_orm(has_many)]
    pub sessions: HasMany<super::sessions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
