//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "feedback")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Option<Uuid>,
    pub rating: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub comments: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub challenges: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub improvements: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub malfunctions: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub attachment_url: Option<String>,
    pub submitted_at: DateTimeWithTimeZone,
    pub anonymous_name: Option<String>,
    pub anonymous_email: Option<String>,
    pub anonymous_matric: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
