//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "focus_events")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub session_id: Uuid,
    pub lost_at: DateTimeWithTimeZone,
    pub regained_at: Option<DateTimeWithTimeZone>,
    pub duration_ms: Option<i32>,
    #[sea_orm(
        belongs_to,
        from = "session_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub sessions: HasOne<super::sessions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
