//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod audit_log;
pub mod autosave_history;
pub mod edit_events;
pub mod exercise_assignments;
pub mod exercises;
pub mod feedback;
pub mod focus_events;
pub mod paste_events;
pub mod questions;
pub mod schema_migrations;
pub mod sessions;
pub mod submissions;
pub mod users;
