//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::audit_log::Entity as AuditLog;
pub use super::autosave_history::Entity as AutosaveHistory;
pub use super::edit_events::Entity as EditEvents;
pub use super::exercise_assignments::Entity as ExerciseAssignments;
pub use super::exercises::Entity as Exercises;
pub use super::feedback::Entity as Feedback;
pub use super::focus_events::Entity as FocusEvents;
pub use super::paste_events::Entity as PasteEvents;
pub use super::questions::Entity as Questions;
pub use super::schema_migrations::Entity as SchemaMigrations;
pub use super::sessions::Entity as Sessions;
pub use super::submissions::Entity as Submissions;
pub use super::users::Entity as Users;
