//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "questions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "questions_exercise_id_question_index_key")]
    pub exercise_id: Uuid,
    #[sea_orm(unique_key = "questions_exercise_id_question_index_key")]
    pub question_index: i32,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    #[sea_orm(column_type = "Text")]
    pub r#type: String,
    #[sea_orm(column_type = "Text")]
    pub language: String,
    #[sea_orm(column_type = "Text")]
    pub starter: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub points: Option<i32>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub test_cases: Option<Json>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub allowed_packages: Option<Json>,
    #[sea_orm(column_type = "Text", nullable)]
    pub required_package: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub documentation_links: Option<Json>,
    #[sea_orm(
        belongs_to,
        from = "exercise_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub exercises: HasOne<super::exercises::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
