//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "sessions_exercise_id_user_id_key")]
    pub exercise_id: Uuid,
    #[sea_orm(unique_key = "sessions_exercise_id_user_id_key")]
    pub user_id: Uuid,
    pub start_time: Option<DateTimeWithTimeZone>,
    pub end_time: Option<DateTimeWithTimeZone>,
    pub duration_limit: Option<String>,
    pub started_at: Option<DateTimeWithTimeZone>,
    pub closed_at: Option<DateTimeWithTimeZone>,
    pub current_question_index: i32,
    pub passed: Option<bool>,
    pub passed_override: Option<bool>,
    pub score: Option<Decimal>,
    #[sea_orm(column_type = "Text", nullable)]
    pub verdict: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub verdict_note: Option<String>,
    pub verdict_by: Option<Uuid>,
    pub verdict_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(
        belongs_to,
        from = "exercise_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub exercises: HasOne<super::exercises::Entity>,
    #[sea_orm(has_many)]
    pub focus_events: HasMany<super::focus_events::Entity>,
    #[sea_orm(has_many)]
    pub submissions: HasMany<super::submissions::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users2",
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users_2: HasOne<super::users::Entity>,
    #[sea_orm(
        belongs_to,
        relation_enum = "Users1",
        from = "verdict_by",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users_1: HasOne<super::users::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
