//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "submissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "submissions_session_id_question_index_key")]
    pub session_id: Uuid,
    #[sea_orm(unique_key = "submissions_session_id_question_index_key")]
    pub question_index: i32,
    #[sea_orm(column_type = "Text")]
    pub response_text: String,
    pub is_final: bool,
    pub is_flagged: bool,
    pub flag_reasons: Option<Vec<String>>,
    #[sea_orm(column_type = "Text", nullable)]
    pub review_note: Option<String>,
    pub submitted_at: DateTimeWithTimeZone,
    pub manually_passed: Option<bool>,
    #[sea_orm(column_type = "JsonBinary")]
    pub dismissed_flags: Json,
    #[sea_orm(column_type = "Text", nullable)]
    pub status: Option<String>,
    pub tests_passed: Option<bool>,
    #[sea_orm(has_many)]
    pub autosave_histories: HasMany<super::autosave_history::Entity>,
    #[sea_orm(has_many)]
    pub edit_events: HasMany<super::edit_events::Entity>,
    #[sea_orm(has_many)]
    pub paste_events: HasMany<super::paste_events::Entity>,
    #[sea_orm(
        belongs_to,
        from = "session_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub sessions: HasOne<super::sessions::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
