//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(column_type = "Text", unique)]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub password_hash: String,
    #[sea_orm(column_type = "Text")]
    pub role: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub audit_logs: HasMany<super::audit_log::Entity>,
    #[sea_orm(has_many)]
    pub feedbacks: HasMany<super::feedback::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

pub use Entity as UsersEntity;
